- Developer:
    - GitHub:
        - icon: github
          href: https://github.com/patrickhere
    - Forgejo:
        - icon: gitea
          href: https://git.hartforge.dev

- External:
    - Cloudflare:
        - icon: cloudflare
          href: https://dash.cloudflare.com
    - WGDashboard:
        - icon: wireguard
          href: https://wireguard.hartforge.dev
    - Ionos:
        - icon: mdi-server
          href: https://my.ionos.com
