services:
  shelfmark:
    image: ghcr.io/calibrain/shelfmark:1.3.3
    container_name: shelfmark
    environment:
      - PUID=0
      - PGID=0
      - SESSION_COOKIE_SECURE=true
      - CALIBRE_WEB_URL=https://books.hartforge.dev
      - AUTH_METHOD=oidc
      - DISABLE_LOCAL_AUTH=true
      - OIDC_DISCOVERY_URL=https://pocket-id.hartforge.dev/.well-known/openid-configuration
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
    env_file:
      - .env
    volumes:
      - ./config:/config
      - /opt/calibre-web/ingest:/books
    ports:
      - "127.0.0.1:8084:8084"
    restart: unless-stopped
    mem_limit: 384m
    security_opt:
      - no-new-privileges:true
