---
collections:
  - name: community.general
    version: ">=12.0.0"
  - name: community.docker
    version: ">=5.1.0"
  - name: community.proxmox
    version: ">=1.6.0"
  - name: community.grafana
    version: ">=2.3.0"
  - name: community.crypto
    version: ">=2.0.0"
  - name: ansible.posix
    version: ">=2.1.0"
  - name: devsec.hardening
    version: ">=10.0.0"
