---
- name: Add Grafana GPG key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: '0644'
  tags: [alloy, install]

- name: Add Grafana apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
    state: present
  tags: [alloy, install]

- name: Install Alloy
  ansible.builtin.apt:
    name: alloy
    state: present
    update_cache: true
  tags: [alloy, install]

- name: Configure Alloy
  ansible.builtin.template:
    src: config.alloy.j2
    dest: /etc/alloy/config.alloy
    mode: '0644'
  notify: restart alloy
  tags: [alloy, configure]

- name: Enable and start Alloy
  ansible.builtin.systemd:
    name: alloy
    enabled: true
    state: started
  tags: [alloy, install]
